[package]
name = "find_mountpoint"
description = "wrap `libc::statfs` to find the mountpoint for a provided path"
version = "0.1.0"
authors = ["Forrest L Norvell <ogd@aoaioxxysz.net>"]
license = "MIT"

[dependencies]
libc = "0.2.22"
